#! /bin/sh

# helper script for starting an Agama instance in a VM

VMDIR=$(mktemp --tmpdir -d agama-vm.XXXXXX)
echo "$VMDIR"
trap 'rm -rf -- "$VMDIR"' INT TERM HUP EXIT

# create a sparse disk image
DISK="$VMDIR/disk"
truncate -s 64G "$DISK"

# use port forwarding like this:
#   https://localhost:4433
#   ssh root@localhost -p 2222
qemu-kvm -m 2G -smp 4 -boot d -drive format=raw,file="$DISK" -nic user,hostfwd=tcp::4433-:443,hostfwd=tcp::2222-:22 -cdrom $1
